models:
  - name: stg_procurements
    description: this tables contains the unpacked version of raw procurement data coming from different sources. No transformation/filtering/cleaning applied.
    config:
      contract:
        enforced: true
    columns:
      - name: buyer
        description: Name of the buyer organization.
        data_type: string
      - name: date_accessed
        description: Date when the data was scraped.
        data_type: string
        constraints:
          - type: not_null
          - type: check
            expression: "regexp_like(date_accessed, '[0-9]{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])')"
            name: date_accessed_pattern_check_proc
      - name: id
        description: Unique identifier of the procurement.
        data_type: string
        constraints:
          - type: not_null
        tests:
          - unique
      - name: procurement_number
        description: Number of the Procurement the bid is related with.
        data_type: integer
      - name: project_id
        description: Project ID assigned to the procurement.
        data_type: string
      - name: publish_date
        description: Date when the procurement has been published on the source website.
        data_type: string
      - name: source
        description: Source code of the procurements.
        data_type: string
        constraints:
          - type: not_null
      - name: title
        description: Title of the procurement content.
        data_type: string
      - name: type
        description: Type of announcement made regarding the procurement.
        data_type: string
    tests:
      - date_accessed_pattern_check


  - name: stg_bids
    description: this tables contains the unpacked version of raw bids data coming from different sources. No transformation/filtering/cleaning applied.
    config:
      contract:
        enforced: true
    columns:
      - name: date_accessed
        description: Date when the data was scraped.
        data_type: string
        constraints:
          - type: not_null
          - type: check
            expression: "regexp_like(column, '[0-9]{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])')"
            name: date_accessed_pattern_check_bid
      - name: procurement_number
        description: Number of the Procurement the bid is related with.
        data_type: integer
        constraints:
          - type: not_null
      - name: source
        description: Source code of the procurements.
        data_type: string
        constraints:
          - type: not_null
      - name: supplier
        description: Name of the bidder.
        data_type: string
      - name: value
        description: Bid monetary value in original string format, including currency.
        data_type: string
        constraints:
          - type: check
            expression: "value  is null OR value  like '¥%'"
            name: bid_value_has_currency_check
    tests:
      - date_accessed_pattern_check
      - bid_value_has_currency