models:
  - name: company_profile_page
    config:
      contract:
        enforced: true
    columns:
      - name: supplier
        data_type: string
        constraints:
          - type: not_null
      - name: title
        data_type: string
        constraints:
          - type: not_null
      - name: bid_amount
        data_type: float
        constraints:
          - type: not_null
      - name: currency
        data_type: string
      - name: is_winner_bid
        data_type: boolean
      - name: total_number_of_bids
        data_type: integer
      - name: total_number_of_winner_bids
        data_type: integer
      - name: buyer
        data_type: string
      - name: type
        data_type: string
      - name: source
        data_type: string
        constraints:
          - type: not_null
      - name: procurement_number
        data_type: integer
      - name: publish_date
        data_type: string


  - name: procurements_page
    config:
      contract:
        enforced: true
    columns:
      - name: winner_supplier
        data_type: string
      - name: title
        data_type: string
        constraints:
          - type: not_null
      - name: winner_bid_amount
        data_type: float
      - name: currency
        data_type: string
      - name: number_of_bids
        data_type: integer
      - name: buyer
        data_type: string
      - name: type
        data_type: string
      - name: source
        data_type: string
        constraints:
          - type: not_null
      - name: procurement_number
        data_type: integer
      - name: publish_date
        data_type: string